### ISSUE TITLE
Does nebula support bulk load or multi host setup?

### ISSUE THREAD

**Issue by lMangoi** [vesoft-inc/nebula#411] opened 2019-05-21 10:49 UTC
Thank you for opening the nebula source code.There are two questions:
1. Does nebula support bulk load data? If yes, are there examples or the manual?
2. If I want to deploy nebula on multi hosts, how should I configure it? Are there any distributed document or architecture introduction?

**Comment by dangleptr** [comment] 2019-05-22 04:01
Sorry,  there is no documents yet.  But you could refer to pr #208 .  
This is a spark job to generate SST files directly.

**Comment by lMangoi** [comment] 2019-05-23 03:54
Thanks for your reply! And there is still a question:
Does nebula support distributed deployment? If yes, I want to deploy tests on multi hosts, how should I configure it?

**Comment by dutor** [comment] 2019-05-24 03:54
@lMangoi Nebula currently lacks many of documents, but we have been working hard on them.

For your question, Nebula's standard installation consists of three directories, i.e. `bin`, `scripts`, `etc`. There are three daemons and one console, aka `nebula-graphd`, `nebula-storaged`, `nebula-metad` and `nebula`. You could infer the roles from their names. Besides, there are some utility scripts in the `scripts` with which you could perform some basic operations on the service, `scripts/nebula.service -h` could show you the usage, concisely.

FYI. there are still no tools to do deployment in a distributed environment, but we are happy and graceful to accept such contributions from the community.

**Comment by sherman-the-tank** [comment] 2019-05-26 15:25
Nebula was designed as a distributed system. But because it's still in the early stage, many tools are missing. You can certainly manually deploy Nebula on multiple hosts. We will provide distributed deployment tools/scripts in the beta release

**Comment by sherman-the-tank** [comment] 2019-05-30 01:30
For this release, we do not suggest to test the multi-host deployment. The coming beta release will provide scripts and commands to manager multiple hosts. Stay tuned

**Comment by sherman-the-tank** [comment] 2019-05-30 05:57
Let's close this now

**Closed by sherman-the-tank** 2019-05-30 05:57 UTC
Labels: question
