### ISSUE TITLE
Create schema failed with batch command.

### ISSUE THREAD

**Issue by zhaodengchang** [vesoft-inc/nebula#1423] opened 2019-12-11 04:26 UTC
```
(user@10.177.28.25) [nearby10_geo]> CREATE SPACE nearby10(partition_num=256); \
                                 -> USE nearby10; \
                                 -> CREATE TAG user(mid int, user_id int, province_name string, consumption_level string); \
                                 -> CREATE TAG poi(mid int, poi_id int, city_name string, poi_star string, poi_consumerlevel string); \
                                 -> CREATE TAG category(mid int, categoryid int, categoryname string); \
                                 -> CREATE TAG cuisine(mid int, cuisineid int, cuisinename string); \
                                 -> CREATE TAG sku(mid int, sku_id int, sku_name string); \
                                 -> CREATE EDGE click(user_mid int, poi_mid int, num double); \
                                 -> CREATE EDGE add_favor(user_mid int, poi_mid int, num double); \
                                 -> CREATE EDGE buy(user_mid int, poi_mid int, num double); \
                                 -> CREATE EDGE buy_reverse(poi_mid int, user_mid int, num double, province_name string, consumption_level string); \
                                 -> CREATE EDGE prefer_category(user_mid int, category_mid int, score double); \
                                 -> CREATE EDGE prefer_cuisine(user_mid int, cuisine_mid int, score double); \
                                 -> CREATE EDGE poi_has_sku(poi_mid int, sku_mid int); \
                                 -> CREATE EDGE poi_has_category(poi_mid int, category_mid int); \
                                 -> CREATE EDGE poi_has_cuisine(poi_mid int, cuisine_mid int); \
                                 -> CREATE EDGE sku_belongto_category(sku_mid int, category_mid int); \
                                 -> CREATE EDGE sku_belongto_cuisine(sku_mid int, cuisine_mid int); 
[ERROR (-8)]: Space not found for `nearby10'
```

Error occurs in Nebula Cluster with 3 machines.

**Comment by Amber1990Zhang** [comment] 2019-12-11 06:14
Thanks for your issue.  If you created a space, you can use it seconds later. If you try another time, it will work.

**Comment by Shylock-Hg** [comment] 2019-12-11 06:43
Seems duplicate with #1352

**Comment by Shylock-Hg** [comment] 2019-12-11 06:44
Duplicate of #1352

**Comment by Shylock-Hg** [comment] 2019-12-12 08:50
Seems caused by read from non-leader raft member which the append log async.

**Comment by Shylock-Hg** [comment] 2020-01-06 08:31
The meta write not perform immediately with replica.

**Closed** 2020-02-28 09:09 UTC
