### ISSUE TITLE
there's a problem with tag's property filtering push-down

### ISSUE THREAD

**Issue by nevermore3** [vesoft-inc/nebula#2727] opened 2021-06-11 06:49 UTC

**Comment by CPWstatic** [comment] 2021-08-28 11:39
This will be fixed by our september version.

**Comment by critical27** [comment] 2021-08-31 11:11
Which one...

**Comment by Sophie-Xie** [comment] 2021-09-16 01:52
> Which one...

@nevermore3 pls confirm the question.

**Comment by nevermore3** [comment] 2021-09-16 02:03
When there are only vertices and no edges, the filtering of vertices is invalid。 
It seems to be related to the execution plan

**Comment by critical27** [comment] 2021-09-17 11:22
@bright-starry-sky has confirmed with @CPWstatic , this is reasonable, because the filter in go only works when edges are valid.

**Comment by critical27** [comment] 2021-09-27 12:37
This is because `go` requires `dst` as a implicit field, and that's why we need a hash join node.
We need to wait all interfaces are explicitly specified, everything will be ok then.

**Comment by bright-starry-sky** [comment] 2021-09-27 14:10
Close this issue. After offline discussion with @CPWstatic , the result is expect.

`CREATE SPACE test (partition_num=1,replica_factor=1, vid_type=fixed_string(30));
USE test;
create tag st1(c1 string)
create edge se1(c1 string)
create edge se2(c1 string)

insert edge se1(c1) values "1" -> "2"@0:("row"), "1" -> "3"@0:("row")
insert vertex st1(c1) values "1":("row"), "2":("row"), "3":("row")


(root@nebula) [test]> go from "1" over se2 where $$.st1.c1 == "row"
+----------+
| se2._dst |
+----------+
+----------+
Empty set (time spent 7382/7947 us)

Tue, 31 Aug 2021 13:27:15 CST

(root@nebula) [test]> 

(root@nebula) [test]> go from "1" over se1 where $$.st1.c1 == "row"
+----------+
| se1._dst |
+----------+
| "2"      |
+----------+
| "3"      |
+----------+
Got 2 rows (time spent 12583/13348 us)

Tue, 31 Aug 2021 13:27:35 CST

(root@nebula) [test]> go from "1" over * where $$.st1.c1 == "row"
+----------+----------+
| se1._dst | se2._dst |
+----------+----------+
| "2"      |          |
+----------+----------+
| "3"      |          |
+----------+----------+
Got 2 rows (time spent 10977/11707 us)

Tue, 31 Aug 2021 13:27:44 CST

(root@nebula) [test]> `

`Execution Plan (optimize time 703 us)

-----+--------------+--------------+------------------------------------------------------------+-----------------------------
| id | name         | dependencies | profiling data                                             | operator info              |
-----+--------------+--------------+------------------------------------------------------------+-----------------------------
|  3 | Project      | 4            | ver: 0, rows: 2, execTime: 137us, totalTime: 148us         | outputVar: [               |
|    |              |              |                                                            |   {                        |
|    |              |              |                                                            |     "colNames": [          |
|    |              |              |                                                            |       "se1._dst"           |
|    |              |              |                                                            |     ],                     |
|    |              |              |                                                            |     "type": "DATASET",     |
|    |              |              |                                                            |     "name": "__Project_3"  |
|    |              |              |                                                            |   }                        |
|    |              |              |                                                            | ]                          |
|    |              |              |                                                            | inputVar: __Filter_2       |
|    |              |              |                                                            | columns: [                 |
|    |              |              |                                                            |   "se1._dst"               |
|    |              |              |                                                            | ]                          |
-----+--------------+--------------+------------------------------------------------------------+-----------------------------
|  4 | GetNeighbors | 0            | {                                                          | outputVar: [               |
|    |              |              | ver: 0, rows: 0, execTime: 194us, totalTime: 129357us      |   {                        |
|    |              |              | "127.0.0.1":3779 exec/total/vertices: 642(us)/65814(us)/1, |     "colNames": [],        |
|    |              |              | total_rpc_time: 129096(us)                                 |     "type": "DATASET",     |
|    |              |              | }                                                          |     "name": "__Filter_2"   |
|    |              |              |                                                            |   }                        |
|    |              |              |                                                            | ]                          |
|    |              |              |                                                            | inputVar: __VAR_0          |
|    |              |              |                                                            | space: 3                   |
|    |              |              |                                                            | dedup: false               |
|    |              |              |                                                            | limit: -1                  |
|    |              |              |                                                            | filter: ($^.st1.c1=="row") |
|    |              |              |                                                            | orderBy: []                |
|    |              |              |                                                            | src: COLUMN[0]             |
|    |              |              |                                                            | edgeTypes: []              |
|    |              |              |                                                            | edgeDirection: OUT_EDGE    |
|    |              |              |                                                            | vertexProps: [             |
|    |              |              |                                                            |   {                        |
|    |              |              |                                                            |     "tagId": 4,            |
|    |              |              |                                                            |     "props": [             |
|    |              |              |                                                            |       "c1"                 |
|    |              |              |                                                            |     ]                      |
|    |              |              |                                                            |   }                        |
|    |              |              |                                                            | ]                          |
|    |              |              |                                                            | edgeProps: [               |
|    |              |              |                                                            |   {                        |
|    |              |              |                                                            |     "type": "5",           |
|    |              |              |                                                            |     "props": [             |
|    |              |              |                                                            |       "_dst"               |
|    |              |              |                                                            |     ]                      |
|    |              |              |                                                            |   }                        |
|    |              |              |                                                            | ]                          |
|    |              |              |                                                            | statProps:                 |
|    |              |              |                                                            | exprs:                     |
|    |              |              |                                                            | random: false              |
-----+--------------+--------------+------------------------------------------------------------+-----------------------------
|  0 | Start        |              | ver: 0, rows: 0, execTime: 4us, totalTime: 55us            | outputVar: [               |
|    |              |              |                                                            |   {                        |
|    |              |              |                                                            |     "colNames": [],        |
|    |              |              |                                                            |     "name": "__Start_0",   |
|    |              |              |                                                            |     "type": "DATASET"      |
|    |              |              |                                                            |   }                        |
|    |              |              |                                                            | ]                          |
-----+--------------+--------------+------------------------------------------------------------+-----------------------------

Tue, 31 Aug 2021 13:45:28 CST
`

**Comment by critical27** [comment] 2022-01-11 07:42
Fixed in #3458

**Closed by critical27** 2022-01-11 07:42 UTC
Labels: type/bug, need to discuss
