### ISSUE TITLE
max_edge_returned_per_vertex does not take effect in v2.5.0

### ISSUE THREAD

**Issue by xiaopqr** [vesoft-inc/nebula#2887] opened 2021-09-13 03:28 UTC
**Describe the bug (__must be provided__)**

max_edge_returned_per_vertex does not take effect in v2.5.0

**Your Environments (__must be provided__)**

* OS: Linux 10-130-166-243.okg-db-graphd.cp01 3.10.0-957.27.2.el7.x86_64 vesoft-inc/nebula-graph#1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Compliler: g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
* CPU: Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
* Commit id: Nothing

**How To Reproduce(__must be provided__)**

1. Step 1:  
    ```UPDATE CONFIGS storage:max_edge_returned_per_vertex=10;```
2. Step 2:  
    ```SHOW CONFIGS;  ```
![image](https://user-images.githubusercontent.com/37445820/133018319-f97764a8-d008-4514-a806-0467c7c378c5.png)
3. Step 3:
    ```GO 1 STEPS FROM 59868671 OVER Singer_song;```
546 results returned

**Comment by bright-starry-sky** [comment] 2021-09-17 02:51
This problem is caused by configuration parameter `local_config`. let refer to the following doc for setting 

https://docs.nebula-graph.io/1.2.1/manual-EN/3.build-develop-and-administration/3.configurations/1.config-persistency-and-priority/

close this one.

**Closed by bright-starry-sky** 2021-09-17 02:51 UTC
Labels: bug
