### ISSUE TITLE
Delete tag from multiple vertices produces Invalid result

### ISSUE THREAD

**Issue by Aiee** [vesoft-inc/nebula#5262] opened 2023-01-16 09:31 UTC
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`) aeacff2e1

**How To Reproduce(__required__)**

```
(root@nebula) [nba]>       FETCH PROP ON player "Tim Duncan" YIELD player.name, player.age

+--------------+------------+
| player.name  | player.age |
+--------------+------------+
| "Tim Duncan" | 42         |
+--------------+------------+
Got 1 rows (time spent 9.768ms/10.481071ms)

Mon, 16 Jan 2023 17:01:48 CST

(root@nebula) [nba]>       FETCH PROP ON player "Tony Parker" YIELD player.name, player.age
+---------------+------------+
| player.name   | player.age |
+---------------+------------+
| "Tony Parker" | 36         |
+---------------+------------+
Got 1 rows (time spent 3.767ms/4.299134ms)

Mon, 16 Jan 2023 17:02:24 CST

(root@nebula) [nba]> 
(root@nebula) [nba]>       DELETE TAG player FROM "Tim Duncan", "Tony Parker";
Execution succeeded (time spent 5.867ms/6.275803ms)

Mon, 16 Jan 2023 17:21:38 CST

(root@nebula) [nba]>       FETCH PROP ON player "Tim Duncan" YIELD player.name, player.age

+-------------+------------+
| player.name | player.age |
+-------------+------------+
|             |            |
+-------------+------------+
Got 1 rows (time spent 4.478ms/4.93895ms)

Mon, 16 Jan 2023 17:21:41 CST

(root@nebula) [nba]>       FETCH PROP ON player "Tony Parker" YIELD player.name, player.age
+-------------+------------+
| player.name | player.age |
+-------------+------------+
+-------------+------------+
Empty set (time spent 4.355ms/4.910096ms)

```

**Expected behavior**

`FETCH PROP ON player "Tim Duncan" YIELD player.name, player.age` should return an empty set

**Additional context**

**Comment by czpmango** [comment] 2023-01-17 06:49
IMHO, returning one empty row is somewhat expected. 
But, we should refine the behavior of the RPC interface `getProps` and make it clearer.

**Comment by Aiee** [comment] 2023-01-18 06:37
This is by design, `Tim Duncan` has multiple tags, so we return the empty row to indicate the vertex still exists, while `Tony Parker` has only one tag named `player`.

**Comment by xtcyclist** [comment] 2023-02-27 09:53
Close this issue as it is by design and won't fix.

**Closed by xtcyclist** 2023-02-27 09:53 UTC
Labels: type/bug, wontfix, severity/none, affects/none
