### ISSUE TITLE
Incorrect query result of match statement

### ISSUE THREAD

**Issue by czpmango** [vesoft-inc/nebula#4908] opened 2022-11-21 06:23 UTC
**Describe the bug (__required__)**
Refer to https://discuss.nebula-graph.com.cn/t/topic/11140/90
The root cause has yet to be located. 
At present, it appears from the execution plan that the results(28 rows of AppendVertices) are incorrectly filtered out.  if remove the with clause or turn off the optimization rule, the results are inconsistent.
I didn't reproduce it. Need to check the impact of property pruning or other optimization rules. Also need to check if it has been fixed in the latest version.

**Your Environments (__required__)**
nebula v3.1.0

**How To Reproduce(__required__)**
Not yet reproduced.

**Expected behavior**
Get the correct query result.

**Comment by xtcyclist** [comment] 2022-12-12 08:15
I checked the execution plan provided by the user. There seeems to be no difference that I can spot. Not sure what the root cause is.

I recommend the user to upgrade it to the the 3.4 version later.

**Comment by czpmango** [comment] 2022-12-22 13:46
> I checked the execution plan provided by the user. There seeems to be no difference that I can spot. Not sure what the root cause is.
> 
> I recommend the user to upgrade it to the the 3.4 version later.

ACK.

**Comment by Sophie-Xie** [comment] 2023-01-29 02:37
Close it first, reopen if it reappears.

**Closed by Sophie-Xie** 2023-01-29 02:37 UTC
Labels: type/bug, priority/hi-pri, need info, severity/minor, affects/none
