### ISSUE TITLE
[TTL] If there is no compaction, the modification to ttl may not take effect

### ISSUE THREAD

**Issue by cangfengzhs** [vesoft-inc/nebula#5134] opened 2022-12-28 06:08 UTC
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
```
create tag ttl_tag2(age int, ttl timestamp) ttl_duration=600, ttl_col="ttl";
insert vertex ttl_tag2(age,ttl) VALUES "1":(10,now());
match (v:ttl_tag2) return v limit 10;  //  visible
alter tag ttl_tag2 ttl_duration=5;
match (v:ttl_tag2) return v limit 10; // not visible
alter tag ttl_tag2 ttl_duration=600;
match (v:ttl_tag2) return v limit 10; // visible
```
**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by HarrisChu** [comment] 2022-12-28 07:06
is it by design?

**Comment by cangfengzhs** [comment] 2022-12-28 07:34
In terms of design, it is right. But functionally, or logically, it is wrong.

**Comment by HarrisChu** [comment] 2022-12-28 08:42
agreed..

if the data is not deleted by compaction, we always compare with the latest ttl duration.
if there're 10 tags, and 5 tags have been deleted, and the other 5 have not.
it may make user confused.

**Comment by HarrisChu** [comment] 2023-01-03 09:41
marked as known issue

**Comment by whitewum** [comment] 2023-01-09 07:44
> @abby-cyber please update doc

I think this is a data error, from the view of a user.

I do not agree to add to doc just as a warning.

@MuYiYong @Sophie-Xie

**Comment by critical27** [comment] 2023-01-09 11:08
It is a data error indeed, but it can't be addressed totally. There is a workaround: forbid alter ttl duration if already has one.

**Comment by critical27** [comment] 2023-01-09 11:15
IIRC, drop TTL is achieved by alter as well. I really don't remember this behavior precisely.

**Comment by HarrisChu** [comment] 2023-01-10 01:16
update more details in v3.4 rc
```
(root@nebula) [(none)]> create space harris(vid_type=fixed_string(10))
Execution succeeded (time spent 9721/23528 us)

Tue, 10 Jan 2023 09:13:34 CST

(root@nebula) [(none)]> use harris
Execution succeeded (time spent 1195/15207 us)

Tue, 10 Jan 2023 09:13:38 CST

(root@nebula) [harris]> create tag ttl_tag2(age int, ttl timestamp) ttl_duration=600, ttl_col="ttl";
Execution succeeded (time spent 5350/18644 us)

Tue, 10 Jan 2023 09:13:40 CST

(root@nebula) [harris]> insert vertex ttl_tag2(age,ttl) VALUES "1":(10,now());
Execution succeeded (time spent 3422/20693 us)

Tue, 10 Jan 2023 09:13:44 CST

(root@nebula) [harris]> match (v:ttl_tag2) return v limit 10;
+-------------------------------------------+
| v                                         |
+-------------------------------------------+
| ("1" :ttl_tag2{age: 10, ttl: 1673313225}) |
+-------------------------------------------+
Got 1 rows (time spent 10824/24590 us)

Tue, 10 Jan 2023 09:13:49 CST

(root@nebula) [harris]> alter tag ttl_tag2 ttl_duration=5;
Execution succeeded (time spent 3936/19855 us)

Tue, 10 Jan 2023 09:13:52 CST

(root@nebula) [harris]> match (v:ttl_tag2) return v limit 10;
+---+
| v |
+---+
+---+
Empty set (time spent 4044/20797 us)

Tue, 10 Jan 2023 09:13:56 CST

(root@nebula) [harris]> alter tag ttl_tag2 ttl_duration=600;
Execution succeeded (time spent 3182/20368 us)

Tue, 10 Jan 2023 09:14:00 CST

(root@nebula) [harris]> match (v:ttl_tag2) return v limit 10;
+-------------------------------------------+
| v                                         |
+-------------------------------------------+
| ("1" :ttl_tag2{age: 10, ttl: 1673313225}) |
+-------------------------------------------+
Got 1 rows (time spent 3734/17573 us)

Tue, 10 Jan 2023 09:14:04 CST

(root@nebula) [harris]> show hosts
+-----------------+-------+----------+--------------+-------------------------------------------+--------------------------------------------+-------------+
| Host            | Port  | Status   | Leader count | Leader distribution                       | Partition distribution                     | Version     |
+-----------------+-------+----------+--------------+-------------------------------------------+--------------------------------------------+-------------+
| "192.168.8.152" | 10030 | "ONLINE" | 77           | "harris:34, nba:34, sf0_1:5, 王者荣耀:4"  | "harris:34, nba:34, sf0_1:24, 王者荣耀:12" | "3.4.0-ent" |
| "192.168.8.152" | 10035 | "ONLINE" | 76           | "harris:33, nba:33, sf0_1:6, 王者荣耀:4"  | "harris:33, nba:33, sf0_1:24, 王者荣耀:12" | "3.4.0-ent" |
| "192.168.8.152" | 10040 | "ONLINE" | 83           | "harris:33, nba:33, sf0_1:13, 王者荣耀:4" | "harris:33, nba:33, sf0_1:24, 王者荣耀:12" | "3.4.0-ent" |
+-----------------+-------+----------+--------------+-------------------------------------------+--------------------------------------------+-------------+
Got 3 rows (time spent 2281/21594 us)

Tue, 10 Jan 2023 09:14:06 CST
```

```

(root@nebula) [harris]> alter tag ttl_tag2 drop (ttl)
Execution succeeded (time spent 3059/15864 us)

Tue, 10 Jan 2023 09:16:28 CST

(root@nebula) [harris]> alter tag ttl_tag2 add (ttl timestamp)
[ERROR (-1005)]: Existed!

Tue, 10 Jan 2023 09:16:38 CST

(root@nebula) [harris]>
```

**Closed** 2023-01-29 03:06 UTC
Labels: type/bug, doc affected, wontfix, severity/minor, affects/master, process/done
