### ISSUE TITLE
Could not use lld in ubuntu OS when compiling nebula with clang 10.0

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#2519] opened 2021-08-13 06:51 UTC
Failed CI [check run](https://github.com/vesoft-inc/nebula/runs/3319409724?check_suite_focus=true)

**ENV**

install-llvm.sh version=10.0.0

**BUILD**

```shell
$ cmake -DNEBULA_USE_LINKER=lld -B build
```

Could use `vesoft/nebula-dev:ubuntu2004` to reproduce it.

**Comment by jiayuehua** [comment] 2021-12-30 08:40
I can't reproduce the issue on fedora30, with lld-8.0， gcc 9.3.  commit 5a4a36b1
![lALPJwY7RAiIdbDNAanNA1U_853_425](https://user-images.githubusercontent.com/3423893/147735434-4fbb3f73-ebd9-46fc-947a-bdaac477ff8b.png)
![lALPJw1WQVIPBD3Mgs0ELA_1068_130](https://user-images.githubusercontent.com/3423893/147735448-e803f682-7ca3-404f-8179-b4027778834b.png)

**Comment by Sophie-Xie** [comment] 2022-04-28 07:50
Discussed it with @yixinglu offline. It does not reproduce and does not affect our environment. We close it first, and reopen it if needed later.

**Closed by Sophie-Xie** 2022-04-28 07:50 UTC
Labels: type/bug, need info
