### ISSUE TITLE
The meta service failed to start due to the existence of pid

### ISSUE THREAD

**Issue by dbacyj** [vesoft-inc/nebula#2907] opened 2021-09-22 01:49 UTC
After the vm goes down, the meta service cannot be started：

![image](https://user-images.githubusercontent.com/72034305/134270452-464218ce-69b3-46b3-8f61-fbeaf9ab97de.png)

The log is as follows：

![image](https://user-images.githubusercontent.com/72034305/134270527-f4f81610-657b-4c45-98d3-d5aa53ad5833.png)

View process does not exist：
![image](https://user-images.githubusercontent.com/72034305/134270567-da67465f-a257-4af7-a9ab-dd582942c4f6.png)

Clear the pid file in the pids directory and then start meta, the problem is solved

**Comment by critical27** [comment] 2021-09-23 05:42
What `pid` is in the `pid file`?

**Comment by dbacyj** [comment] 2021-09-24 03:58
> What `pid` is in the `pid file`?
 didn't view it

**Comment by Sophie-Xie** [comment] 2022-04-24 01:28
The issue is not reproduced, close it first, and reopen it if necessary.

**Closed by Sophie-Xie** 2022-04-24 01:28 UTC
Labels: type/bug, need info
