### ISSUE TITLE
tutorial is broken: `Host not enough!`

### ISSUE THREAD

**Issue by dcsan** [vesoft-inc/nebula#5659] opened 2023-07-28 07:02 UTC
going through the quickstart i have the DB running as a docker extension and have logged in.

https://docs.nebula-graph.io/3.5.0/2.quick-start/1.quick-start-workflow/

`CREATE SPACE bverse(partition_num=10, replica_factor=1, vid_type=fixed_string(30));`

gives the error `Host not enough`

tried reducing partitions, no luck

digging around i found something about setting up hosts

`ADD HOSTS 192.168.10.100:9779, 192.168.10.101:9779, 192.168.10.102:9779;`

which runs OK...

but `CREATE SPACE` still fails.

is there a getting started that actually works? this isn't very reassuring.

**Comment by wey-gu** [comment] 2023-07-28 08:04
Dear @dcsan ,

Sorry for the bad first impression, it seems you deployed a cluster in the first run!👍🏻

ADD HOSTS is an action to activate storaged hosts, while the service need some time to be fully up if they were not activated for a while.

Could you please query `SHOW HOSTS` to see if they are ONLINE now?

**Comment by wey-gu** [comment] 2023-07-28 08:07
Actually, the easiest way to quickly get started from on the server side(rather than the docker extension on the desktop) should be with Docker-Compose, see [here](https://docs.nebula-graph.io/3.5.0/4.deployment-and-installation/2.compile-and-install-nebula-graph/3.deploy-nebula-graph-with-docker-compose/), which ideally should cover the `ADD HOSTS` automatically in the initial go.

We'll improve the docs!

Thanks again~~

**Comment by dcsan** [comment] 2023-07-28 11:57
"status offline" 
![image](https://github.com/vesoft-inc/nebula/assets/514002/9f714bbb-0aa8-4ddf-a26f-2dc3e07e24ba)

so the quickstart using a docker extension is NOT expected to work?
that did seem a nice way to get going, more slick than even neo4j. 

the docker verison says:
> Starting from NebulaGraph version 3.1.0, nebula-docker-compose automatically starts a NebulaGraph Console docker container and adds the storage host to the cluster (i.e. ADD HOSTS command).


But if even the most basic quickstart has these type of bugs... 😅

```
git clone -b release-3.5 https://github.com/vesoft-inc/nebula-docker-compose.git
docker-compose up -d
```

so then the connection string for with python would be... ?

**Comment by wey-gu** [comment] 2023-07-28 15:17
> so the quickstart using a docker extension is NOT expected to work?

Sorry didn't mean that and docker extension is supposed to work! With only one click if we are on the docker **desktop** like [here](https://www.docker.com/blog/distributed-cloud-native-graph-database-nebulagraph-docker-extension/).

For the initial desktop playing it's the most recommended way :).

I thought you are on a server(as you started with a cluster in the issue), thus recommending the docker-compose way(instead of the extension way), with docker-compose, everything should be up and running after `docker-compose up -d` w/o extra steps.

> And regarding
> ![image](https://github.com/vesoft-inc/nebula/assets/514002/9f714bbb-0aa8-4ddf-a26f-2dc3e07e24ba)

For the `ADD HOSTS` was done and still they are offline, we could then check the logs of storaged on what it complains about, which could be due to the ports were not open for the clustering or other issues.

> But if even the most basic quickstart has these type of bugs... 😅

Sorry for this, also it's more than welcome to help improve our docs if you would like to, either to click the pencil from the corresponding page or via https://github.com/vesoft-inc/nebula-docs.

> so then the connection string for with python would be... ?

I would recommend https://github.com/wey-gu/ipython-ngql if you are try it the first time for playing NebulaGraph with python. For application layers, use https://github.com/vesoft-inc/nebula-python

**Comment by dcsan** [comment] 2023-07-28 19:05
hiya - no I'm on a mac desktop for development. 

I installed the docker extension, opened a browser to login to the DB, it's all running. But I cannot write any data - see the error above.
After reading all this, I'm still not sure how do I fix the extension to work?

ADD HOSTS was mentioned in the docs as a solution to 

I'm on a mac with M2 chip - is that supported? there were some docker problems a year ago but mostly working now.

I could try the whole dockerfile approach but I'm not running this server side now.
But things are going to be pretty messy cos the extension is running so i assume there will be port collisions... and of course I don't want all that running in the background, as an invisible docker system extension if it's broken. So I'd need to dig around how to uninstall the extension first I assume.

so this 'offline' status means it wasn't able to start... something? where can i find logs to diagnose?

![image](https://github.com/vesoft-inc/nebula/assets/514002/73c7adc8-de5a-41ad-b8ba-a2db9e099d8a)

**Comment by dcsan** [comment] 2023-07-28 19:08
I restarted the whole docker desktop give it a few minutes to startup, and still get the same condition:

![image](https://github.com/vesoft-inc/nebula/assets/514002/5b6b2eca-178f-45b0-bac3-df88dc2e7e58)

**Comment by dcsan** [comment] 2023-07-28 19:10
> For the ADD HOSTS was done and still they are offline, we could then check the logs of storaged on what it complains about, which could be due to the ports were not open for the clustering or other issues.

where can i find these logs?

**Comment by wey-gu** [comment] 2023-07-29 01:29
> I restarted the whole docker desktop give it a few minutes to startup, and still get the same condition:
> 
> 
> 
> ![image](https://github.com/vesoft-inc/nebula/assets/514002/5b6b2eca-178f-45b0-bac3-df88dc2e7e58)
> 
> 
> 
> 

Ok so the previous capture was actually docker compose? If so plz do so instead:

`ADD HOSTS "storaged0":9779,"storaged1":9779,"storaged2":9779'`

**Comment by wey-gu** [comment] 2023-07-29 01:31
> hiya - no I'm on a mac desktop for development. 
> 
> 
> 
> I installed the docker extension, opened a browser to login to the DB, it's all running. But I cannot write any data - see the error above.
> 
> After reading all this, I'm still not sure how do I fix the extension to work?
> 
> 
> 
> `ADD HOSTS` was mentioned in the docs as a solution to `Host not enough`
> 
> 
> 
> I'm on a mac with M2 chip - is that supported? there were some docker problems a year ago but mostly working now.
> 
> 
> 
> I could try the whole dockerfile approach but I'm not running this server side now.
> 
> But things are going to be pretty messy cos the extension is running so i assume there will be port collisions... and of course I don't want all that running in the background, as an invisible docker system extension if it's broken. So I'd need to dig around how to uninstall the extension first I assume.
> 
> 
> 
> so this 'offline' status means it wasn't able to start... something? where can i find logs to diagnose?
> 
> 
> 
> ![image](https://github.com/vesoft-inc/nebula/assets/514002/73c7adc8-de5a-41ad-b8ba-a2db9e099d8a)
> 
> 
> 
> 

And if we already have docker compose based cluster running it'll impact the extension based service, we should remove one to enable the other to work.

Apple chip should work( we are Mac users too)😊

**Comment by dcsan** [comment] 2023-07-29 02:14
No, the top terminal screenshot was the terminal inside the docker extension. I haven't tried the dockercompose method yet. I uninstalled the extension so I guess i can try via the dc up method.

thanks for all your help!  will try later.

**Comment by wey-gu** [comment] 2023-07-29 02:50
OK, if it's inside the docker extension, it should be done without needing of manually add hosts, as I implemented this via [the extension](https://github.com/nebula-contrib/nebulagraph-docker-ext/pull/17) itself, maybe something is wrong.

On docker desktop, extension is the recommended way to go. Could you do via the get started inside the docker extension window?(when dc is confirmed to be stopped) It guided how to add hosts although, too.

**Comment by QingZ11** [comment] 2023-12-18 10:57
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊

**Closed by QingZ11** 2023-12-18 10:57 UTC
Labels: type/bug, severity/none, affects/none
