### ISSUE TITLE
Could not create tag index again with same name as deleted index

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#2641] opened 2021-06-30 06:24 UTC
```
(root@nebula) [nba]> show tag indexes;
+-------------------------+
| Names                   |
+-------------------------+
| "company_index"         |
+-------------------------+
| "player_age_name_index" |
+-------------------------+
| "team_name_index"       |
+-------------------------+
Got 3 rows (time spent 1203/1443 us)

Wed, 30 Jun 2021 14:21:35 CST

(root@nebula) [nba]> create tag index player_age_index on player(age);
[ERROR (-1005)]: Existed!

Wed, 30 Jun 2021 14:21:37 CST

(root@nebula) [nba]>
```

Before above steps, I dropped the `player_age_index` by:

```
> drop tag index player_age_index;
```

**Comment by bright-starry-sky** [comment] 2021-09-01 01:48
I think , the error was not caused by the same index name. the real reason is that there are duplicate columns. for example:
tag t1 (c1, c2, c3)
create index i1 (c1, c2) <----- allow
create index i2(c1 ,c2) <------ not allow, because the same columns of index is exist with i1.

I will close this issue if there is no other reason.

**Closed** 2021-11-25 10:11 UTC
Labels: bug
