### ISSUE TITLE
Support datatype `datetime`

### ISSUE THREAD

**Issue by knightXun** [vesoft-inc/nebula#1727] opened 2020-02-06 07:25 UTC
please support new datatype `datetime`. 
when i import ldbc generate data, I must treate datetime as string. This not a natural way,

Related issue: #1631

**Comment by Amber1990Zhang** [comment] 2020-02-06 08:10
pr #1450

**Comment by jude-zhu** [comment] 2020-05-26 09:28
duplicate of #1727

**Comment by jude-zhu** [comment] 2021-04-13 06:22
Already supported in Nebula 2.x

**Closed by jude-zhu** 2021-04-13 06:22 UTC
Labels: feature, v2.0
