### ISSUE TITLE
Drop space and the folder was removed but the disk space was not released

### ISSUE THREAD

**Issue by pengweisong** [vesoft-inc/nebula#5157] opened 2022-12-29 09:18 UTC
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

https://discuss.nebula-graph.com.cn/t/topic/11776/5
When the space was dropped, the space directory was removed successfully, but the spaces used by sst was not released successfully.

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`) 3.2

**How To Reproduce(__required__)**

The reason has not been located, guess it may have sth to do with the compaction: 
1. insert lot of data
2. submit a compact job
3. drop the space

**Expected behavior**

The space is released successfully.

**Additional context**

**Comment by HarrisChu** [comment] 2022-12-29 09:34
interesting..
do we `rocksdb::CancelAllBackgroundWork` when we remove the space?

**Comment by pengweisong** [comment] 2022-12-29 09:57
> 



> interesting.. do we `rocksdb::CancelAllBackgroundWork` when we remove the space?

RocksEngine::stop() has called it, but we did not call stop when drop space.. I'll add it.

What's more, we may should call rocksdb::Close() when deconstruct the RocksEngine.

**Comment by HarrisChu** [comment] 2023-01-03 09:34
could not reproduce

**Comment by Sophie-Xie** [comment] 2023-01-29 02:38
Close it first, reopen if it reappears.

**Closed by Sophie-Xie** 2023-01-29 02:38 UTC
Labels: type/bug, need info, severity/none, affects/none
