### ISSUE TITLE
Return value is Empty set

### ISSUE THREAD

**Issue by llinzhe** [vesoft-inc/nebula#4834] opened 2022-11-07 14:20 UTC
**Describe the bug (__required__)**
When the session does not select the graph space, using the graph space selection statement and data query statement, the return value is null.

**Your Environments (__required__)**

* OS: centos 7
* Compiler: g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
**How To Reproduce(__required__)**

```cmd
(root@nebula) [(none)]> :param p0 => 'account001';
(root@nebula) [(none)]> yield $p0
+--------------+
| $p0          |
+--------------+
| "account001" |
+--------------+
Got 1 rows (time spent 325/768 us)

(root@nebula) [(none)]> use userProfile;  MATCH (n1: account)-[r: login*2]-( n2: account) WHERE  n1.account.accountUuid ==$p0  RETURN n2.account.accountUuid as accountUuid
+-------------+
| accountUuid |
+-------------+
+-------------+
```

**Expected behavior**
I expect the graph space selection statement to be executed along with the data query statement and return the query result

**Additional context**
nebula-core:3.3

**Comment by wey-gu** [comment] 2022-11-08 07:08
Interesting, I cannot reproduce in 3.2.0

```
(root@nebula) [test]> use basketballplayer;match (n:`player`) where n.player.name == "Tim Duncan" return *
+----------------------------------------------------+
| n                                                  |
+----------------------------------------------------+
| ("player100" :player{age: 42, name: "Tim Duncan"}) |
| ("player700" :player{age: 42, name: "Tim Duncan"}) |
+----------------------------------------------------+
Got 2 rows (time spent 7228/13821 us)

Tue, 08 Nov 2022 15:06:44 CST

(root@nebula) [basketballplayer]> :param p0 => 'Tim Duncan';
(root@nebula) [basketballplayer]> use basketballplayer;yield $p0
+--------------+
| $p0          |
+--------------+
| "Tim Duncan" |
+--------------+
Got 1 rows (time spent 1819/9157 us)

Tue, 08 Nov 2022 15:07:06 CST

(root@nebula) [basketballplayer]> use basketballplayer;match (n:`player`) where n.player.name == $p0 return *
+----------------------------------------------------+
| n                                                  |
+----------------------------------------------------+
| ("player700" :player{age: 42, name: "Tim Duncan"}) |
| ("player100" :player{age: 42, name: "Tim Duncan"}) |
+----------------------------------------------------+
Got 2 rows (time spent 8026/15345 us)
```

**Comment by czpmango** [comment] 2022-12-07 10:05
I cannot reproduce it.

**Comment by czpmango** [comment] 2022-12-07 10:10
I cannot reproduce it.

**Comment by wey-gu** [comment] 2022-12-12 03:21
ping @llinzhe , any more context on how to reproduce it?

**Comment by llinzhe** [comment] 2022-12-12 10:45
That's all there is.

**Comment by Sophie-Xie** [comment] 2022-12-27 01:27
Sorry. We can't reproduce it, will close it. If you have some new info, open it again. Thanks.

**Closed by Sophie-Xie** 2022-12-27 01:27 UTC
Labels: type/bug, need info, severity/none, affects/none
