### ISSUE TITLE
Default values ​​not supported when inserting vertices/edges

### ISSUE THREAD

**Issue by zlcook** [vesoft-inc/nebula#989] opened 2019-09-27 07:22 UTC
**Describe the bug(__must be provided__)**

 Default values ​​not supported when inserting vertices/edges.

**Expected behavior**
* Insert a Vertex 
```
(user@xxx) [pay_card_graph]> describe tag merchant;
=========================
| Field        | Type   |
=========================
| merchantNo   | string |
-------------------------
| merchantName | string |
-------------------------
Got 2 rows (Time spent: 1500/2485 us)

(user@xxx) [pay_card_graph]> INSERT VERTEX merchant(merchantNo) VALUES hash("beijingbus123"):("beijingbus123");
[ERROR (-8)]: Wrong number of props
```
* Insert an Edge 
```
(user@xxx) [pay_card_graph]> describe edge merchant2biz_card;
========================
| Field       | Type   |
========================
| merchant_no | string |
------------------------
Got 1 rows (Time spent: 1789/2843 us)

(user@xxx) [pay_card_graph]> INSERT EDGE merchant2biz_card() VALUES hash("merchant123") -> hash("biz_card123"):();
[ERROR (-8)]: Wrong number of props
```

**Comment by darionyaphet** [comment] 2019-09-27 07:45
#860

**Comment by jude-zhu** [comment] 2019-11-18 06:57
Duplicate of #631

**Closed by jude-zhu** 2019-11-18 06:57 UTC
Labels: duplicate
