### ISSUE TITLE
Query  destination vertexes has different tags, nonexistent props should return null

### ISSUE THREAD

**Issue by laura-ding** [vesoft-inc/nebula#605] opened 2019-07-10 06:44 UTC
Now the storaged nonsupport returns the data of destination vertexes has diff tags, and the graphd should handle the nonexistent props of the vertex.

**Comment by sherman-the-tank** [comment] 2019-07-11 07:46
Indeed. This depends on the NULL value support

**Comment by jude-zhu** [comment] 2019-10-29 01:32
Duplicate of #1135

**Closed** 2019-11-28 06:26 UTC
Labels: R201910_RC2, defect, duplicate
