### ISSUE TITLE
job time is incorrect

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula#3673] opened 2022-01-10 07:33 UTC
```
(root@nebula) [s1]> show job 4
+----------------+---------------+------------+----------------------------+----------------------------+
| Job Id(TaskId) | Command(Dest) | Status     | Start Time                 | Stop Time                  |
+----------------+---------------+------------+----------------------------+----------------------------+
| 4              | "COMPACT"     | "FINISHED" | 2022-01-10T07:27:18.000000 | 2022-01-10T07:27:18.000000 |
| 0              | "127.0.0.1"   | "FINISHED" | 2022-01-10T07:27:18.000000 | 2022-01-10T07:27:19.000000 |
| 1              | "127.0.0.1"   | "FINISHED" | 2022-01-10T07:27:18.000000 | 2022-01-10T07:27:19.000000 |
| 2              | "127.0.0.1"   | "FINISHED" | 2022-01-10T07:27:18.000000 | 2022-01-10T07:27:19.000000 |
| 3              | "127.0.0.1"   | "FINISHED" | 2022-01-10T07:27:18.000000 | 2022-01-10T07:27:19.000000 |
| 4              | "127.0.0.1"   | "FINISHED" | 2022-01-10T07:27:18.000000 | 2022-01-10T07:27:19.000000 |
| 5              | "127.0.0.1"   | "FINISHED" | 2022-01-10T07:27:18.000000 | 2022-01-10T07:27:19.000000 |
+----------------+---------------+------------+----------------------------+----------------------------+
Got 7 rows (time spent 1948/6453 us)

Mon, 10 Jan 2022 15:27:18 CST

(root@nebula) [s1]> show jobs
+--------+----------------+------------+----------------------------+----------------------------+
| Job Id | Command        | Status     | Start Time                 | Stop Time                  |
+--------+----------------+------------+----------------------------+----------------------------+
| 4      | "COMPACT"      | "FINISHED" | 2022-01-10T07:27:18.000000 | 2022-01-10T07:27:18.000000 |
| 3      | "DATA_BALANCE" | "FAILED"   | 2022-01-10T07:24:47.000000 | 2022-01-10T07:24:53.000000 |
+--------+----------------+------------+----------------------------+----------------------------+
Got 2 rows (time spent 4575/12908 us)

Mon, 10 Jan 2022 15:30:23 CST
```

1. should display the real time, e.g. 2022-01-10T07:27:18.123456
2. or display without microseconds， e.g.  2022-01-10T07:27:18

**Comment by liwenhui-soul** [comment] 2022-01-13 03:11
seems like caused by wrong time zone

**Comment by critical27** [comment] 2022-03-15 04:12
Will fixed in next major version, close for now

**Closed by critical27** 2022-03-15 04:12 UTC
Labels: type/bug, wontfix
