### ISSUE TITLE
bug: when meta is down, `show hosts metad` result is wrong

### ISSUE THREAD

**Issue by QingZ11** [vesoft-inc/nebula#3409] opened 2021-12-06 02:06 UTC
* version: v2.6.1

* description: when a meta service is down, `show hosts metad` shows it still online not offline.

* ref: [https://discuss.nebula-graph.com.cn/t/topic/6764](https://discuss.nebula-graph.com.cn/t/topic/6764)

**Comment by liuyu85cn** [comment] 2021-12-06 02:59
I agree this is a bug, but actually, it is the original design:
the key feature of  "show hosts meta" is to check "GitInfoSha".
we want to check this to see if an upgrade succeeded,
and the "Online/Offline" column is hard coded as "Online";

However, user won't care about this, they may get confused by this bug. 
In my opinion, we have some solution for this:

1. Add a meta client to meta itself. Let all meta follower send heartbeat to meta leader. 
    
   the problem is: it is a litter weird that a meta server also have a meta client. 
   And this why we (with DanglePtr) decide to hard code the status "Online".

2. raft layer of meta may have some clue, we can get to determine the status of meta follower.

    The problem is: 
    We need to keep a vector to record last succeeded RPC call for all it's follower,
    Raft don't need this, and I don't think it is a good idea to 
    add this thing,  just for a nearly never used feature "show hosts meta".

3. when trigger "show hosts meta". we do some simple network check. 

    The problem is: Code for this may really ugly. 

If we really need to fix this, I prefer the first one.

**Comment by panda-sheep** [comment] 2021-12-06 03:33
> I agree this is a bug, but actually, it is the original design: the key feature of "show hosts meta" is to check "GitInfoSha". we want to check this to see if an upgrade succeeded, and the "Online/Offline" column is hard coded as "Online";
> 
> However, user won't care about this, they may get confused by this bug. In my opinion, we have some solution for this:
> 
> 1. Add a meta client to meta itself. Let all meta follower send heartbeat to meta leader.
>    the problem is: it is a litter weird that a meta server also have a meta client.
>    And this why we (with DanglePtr) decide to hard code the status "Online".
> 2. raft layer of meta may have some clue, we can get to determine the status of meta follower.
>    The problem is:
>    We need to keep a vector to record last succeeded RPC call for all it's follower,
>    Raft don't need this, and I don't think it is a good idea to
>    add this thing,  just for a nearly never used feature "show hosts meta".
> 3. when trigger "show hosts meta". we do some simple network check.
>    The problem is: Code for this may really ugly.
> 
> If we really need to fix this, I prefer the first one.

Good， 👍
I think the leader of raft can keep all the follower's last heartbeat or rpc success information.
This plan is more natural.

**Comment by critical27** [comment] 2021-12-28 06:14
Could do it after 1230

**Comment by critical27** [comment] 2022-03-15 04:13
Will fixed in next major version, close for now

**Closed by critical27** 2022-03-15 04:13 UTC
Labels: type/bug, wontfix
