### ISSUE TITLE
Failed job cannot be stopped

### ISSUE THREAD

**Issue by NicolaCage** [vesoft-inc/nebula#4247] opened 2022-05-11 06:02 UTC
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/37568394/167779411-af493e05-3c96-4a1e-9ce4-319a3d8c9e0c.png">
<img width="206" alt="image" src="https://user-images.githubusercontent.com/37568394/167779460-6013d5c1-4e59-4de5-988f-b71f3ecc3ad9.png">

**Comment by NicolaCage** [comment] 2022-05-11 06:11
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/37568394/167780710-1f6e01c1-2be0-48a9-869a-cb03aedb534c.png">
The running task cannot be stopped

**Comment by NicolaCage** [comment] 2022-05-11 06:14
nebula version： Community v3.1.0

**Comment by critical27** [comment] 2022-07-19 03:30
The error message has say it failed to persistent job info. ZONE_BALANCE support stopped (the stop job operation failed), see the sheet I send you guys before. It is quite a different problem with the title of the issue.

I'll close it later if there is no more update

**Comment by critical27** [comment] 2022-07-20 01:39
BTW, we can only stop the latest balance job. FAILED of outdate job should not stop. This is by design

**Closed** 2022-08-08 01:33 UTC
Labels: type/bug

**Comment by critical27** [comment] 2022-08-08 01:53
Some problem has been fixed in #4460, again, failed job cannot and should not be stopped
