### ISSUE TITLE
support space() function to query the current space

### ISSUE THREAD

**Issue by steppenwolfyuetong** [vesoft-inc/nebula#599] opened 2019-07-09 07:17 UTC
As title

**Comment by sherman-the-tank** [comment] 2019-07-10 05:38
Do you want something like
```
YIELD space()
```

If so, I agree with you

**Comment by steppenwolfyuetong** [comment] 2019-07-10 06:10
> Do you want something like
> 
> ```
> YIELD space()
> ```
> 
> If so, I agree with you

Yeah

**Comment by sherman-the-tank** [comment] 2019-07-13 13:47
This is a dup of #427 , so closing this now

**Comment by whitewum** [comment] 2019-08-15 08:32
#427 
#615 paritally fix this problem. But I do think
yield space() make sense.

**Comment by jude-zhu** [comment] 2019-11-06 03:32
Duplicate of #427

**Closed** 2019-11-21 08:08 UTC
Labels: duplicate, feature, good first issue
